USE [master]
GO
/****** Object:  Database [PruebaApi]    Script Date: 26/02/2022 10:53:06 a. m. ******/
CREATE DATABASE [PruebaApi]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'PruebaApi', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\PruebaApi.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'PruebaApi_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\PruebaApi_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [PruebaApi] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [PruebaApi].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [PruebaApi] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [PruebaApi] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [PruebaApi] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [PruebaApi] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [PruebaApi] SET ARITHABORT OFF 
GO
ALTER DATABASE [PruebaApi] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [PruebaApi] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [PruebaApi] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [PruebaApi] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [PruebaApi] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [PruebaApi] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [PruebaApi] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [PruebaApi] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [PruebaApi] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [PruebaApi] SET  DISABLE_BROKER 
GO
ALTER DATABASE [PruebaApi] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [PruebaApi] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [PruebaApi] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [PruebaApi] SET ALLOW_SNAPSHOT_ISOLATION OFF   
GO
ALTER DATABASE [PruebaApi] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [PruebaApi] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [PruebaApi] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [PruebaApi] SET RECOVERY FULL 
GO
ALTER DATABASE [PruebaApi] SET  MULTI_USER 
GO
ALTER DATABASE [PruebaApi] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [PruebaApi] SET DB_CHAINING OFF 
GO
ALTER DATABASE [PruebaApi] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [PruebaApi] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [PruebaApi] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [PruebaApi] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'PruebaApi', N'ON'
GO
ALTER DATABASE [PruebaApi] SET QUERY_STORE = OFF  
GO
USE [PruebaApi]
GO
/****** Object:  Table [dbo].[Usuarios]    Script Date: 26/02/2022 10:53:07 a. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Usuarios](
	[Id_Usuario] [int] NOT NULL,  
	[Nombres] [varchar](100) NOT NULL,
	[Apellidos] [varchar](100) NOT NULL,
	[Tipo_Documento] [varchar](50) NOT NULL,
	[Fecha_Nacimiento] [date] NOT NULL,
	[Valor_a_Ganar] [float] NOT NULL,
	[Estado_Civil] [varchar](100) NOT NULL,
 CONSTRAINT [PK_Usuarios] PRIMARY KEY CLUSTERED 
(
	[Id_Usuario] ASC  
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
INSERT [dbo].[Usuarios] ([Id_Usuario], [Nombres], [Apellidos], [Tipo_Documento], [Fecha_Nacimiento], [Valor_a_Ganar], [Estado_Civil]) VALUES (168954656, N'JOSE DEL CARMEN', N'BARRIOS JIMENEZ', N'CC', CAST(N'2021-06-03' AS Date), 6000000, N'CASADO')
INSERT [dbo].[Usuarios] ([Id_Usuario], [Nombres], [Apellidos], [Tipo_Documento], [Fecha_Nacimiento], [Valor_a_Ganar], [Estado_Civil]) VALUES (940624181, N'RAUL ALFONSO ', N'CUDRIS SINNING', N'CC', CAST(N'2022-02-08' AS Date), 15000, N'CASADA')
INSERT [dbo].[Usuarios] ([Id_Usuario], [Nombres], [Apellidos], [Tipo_Documento], [Fecha_Nacimiento], [Valor_a_Ganar], [Estado_Civil]) VALUES (1075989877, N'FREDDY ', N'NAVARRO RODRIGUEZ', N'CC', CAST(N'2021-08-12' AS Date), 200000, N'SOLTERO')
INSERT [dbo].[Usuarios] ([Id_Usuario], [Nombres], [Apellidos], [Tipo_Documento], [Fecha_Nacimiento], [Valor_a_Ganar], [Estado_Civil]) VALUES (1658988777, N'JOSE LUIS', N'DIAZ JULIO', N'CC', CAST(N'2021-10-12' AS Date), 150000, N'SOLTERO')
GO
USE [master]
GO
ALTER DATABASE [PruebaApi] SET  READ_WRITE 
GO
